name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
          check-latest: true

      - name: Install
        run: yarn --frozen-lockfile
      - name: Lint test
        run: yarn lint
      - name: Build test
        run: yarn build
